friendlygas_project/core/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^ajax/location_request/$', views.location_request, name='location_request'),
	url(r'^ajax/near_gas_stations/$', views.near_gas_stations, name='near_gas_stations'),
	url(r'^ajax/update_entity_attributes$', views.update_entity_attributes, name='update_entity_attributes'),
	url(r'^ajax/update_update_ckan$', views.update_ckan, name='update_ckan'),
]

friendlygas_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [	
	url(r'^', include('friendlygas_project.core.urls', namespace="core")),
    url(r'^admin/', admin.site.urls),        
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

friendlygas_project/core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

friendlygas_project/core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import JsonResponse
from orionclient import OrionClient
from django.conf import settings
import json
import datetime
import pytz
import csv
import os
from ckanapi import RemoteCKAN
from django.contrib.staticfiles.storage import staticfiles_storage
import json

from django.shortcuts import render
# Create your views here.

def index(request):
	template_name = 'core/home.html'
	return render(request, template_name, {})

def location_request(request):
	latitude = request.GET.get('latitude', None)
	longitude = request.GET.get('longitude', None)
	template_name = 'core/home.html'
	context = {
		'latitude': latitude,
		'longitude': longitude
	}
	return JsonResponse(context)
	# return render(request, template_name, context)

def get_orion_client():
	client = OrionClient(
            orion_host_url='104.131.81.74',
            orion_host_port='1026',
            username='root',
            password='violao123',
			authMethod=None,            
			orion_token_url=None,
            )
	return client

def near_gas_stations(request):
	latitude = request.GET.get('latitude', None)
	longitude = request.GET.get('longitude', None)
	radius = request.GET.get('radius', None)
	orion_client = get_orion_client()
	near_gas_stations = orion_client.query_entity('GasStation', latitude, longitude, radius)	
	return JsonResponse(near_gas_stations)	

def save_gas_stations_as_csv(orion_client):    
	csv_header = []
	csv_rows = []  
	gas_stations = orion_client.fetch_entity(type_id='GasStation')
	for gas_station_key in gas_stations:
		gas_station = orion_client.fetch_entity(type_id='GasStation', entity_id=gas_station_key)
		gas_station.pop('star_votes', None)
		if not csv_header:
			csv_header.append(gas_station.keys())        
		csv_rows.append(list(gas_station.values()))
	file_name = 'gas_stations_%s.csv' % datetime.datetime.now().__str__()
	file_path = 'friendlygas_project/core/media/' + file_name	
	with open(file_path, "wb") as f:
		writer = csv.writer(f)
		writer.writerows(csv_header + csv_rows)
	return file_name

def gas_stations_json(orion_client):
	json_file_path = 'friendlygas_project/core/media/gas_stations_data.json'
	if not os.path.isfile(json_file_path):		
		gas_stations = orion_client.fetch_entity(type_id='GasStation')
		gas_stations_map = {}
		for gas_station_key in gas_stations:
			gas_station = orion_client.fetch_entity(type_id='GasStation', entity_id=gas_station_key)
			gas_stations_map[gas_station_key] = gas_stations[gas_station_key]
		js = json.dumps(gas_stations_map, sort_keys=True, indent=4, separators=(',', ': '))
		with open(json_file_path, 'w') as f:
		    f.write(js)
	return json_file_path

def save_map_as_csv(gas_stations_map):
	csv_header = []
	csv_rows = []
	for key, value in gas_stations_map.items():		
		value.pop('star_votes', None)
		if not csv_header:
			csv_header.append(value.keys())        
		csv_rows.append(list(value.values()))
	file_name = 'gas_stations_%s.csv' % datetime.datetime.now().__str__()
	file_path = 'friendlygas_project/core/media/' + file_name	
	with open(file_path, "wb") as f:
		writer = csv.writer(f)
		writer.writerows(csv_header + csv_rows)
	return file_name

def update_json_and_save_csv(orion_client, entity_id):
	json_file_path = gas_stations_json(orion_client)
	gas_stations_map = json.load(open(json_file_path))
	gas_station = orion_client.fetch_entity(type_id='GasStation', entity_id=entity_id)	
	gas_stations_map[entity_id] = gas_station
	js = json.dumps(gas_stations_map, sort_keys=True, indent=4, separators=(',', ': '))
	with open(json_file_path, 'w') as f:
		f.write(js)
	return save_map_as_csv(gas_stations_map)

def update_ckan_database_resource(domain, entity_id):
	ua = 'ckanapiexample/1.0 (+http://example.com/my/website)'	
	client = RemoteCKAN('http://104.236.54.23', apikey='eb5346ab-0c53-4b1f-a0a4-f4be797db23b', user_agent=ua)
	# file_name = save_gas_stations_as_csv(get_orion_client())
	file_name = update_json_and_save_csv(get_orion_client(), entity_id)
	file_path_csv = 'friendlygas_project/core/media/' + file_name
	file_path_json = 'friendlygas_project/core/media/gas_stations_data.json'
	date = str(datetime.datetime.now(pytz.timezone('America/Recife')))
	client.action.resource_create(	
	    package_id='ac335d1a-098c-4f18-882c-03950ddc5d7c',
	    name = 'Postos de Combustíveis - Natal - RN - ' + date,
	    description = 'Este arquivo contém as informações dos Postos de Combustíveis de Natal - RN.',
	    format = 'csv',
	    upload = open(file_path_csv, 'rb'),
	    url = 'http://' + domain + '/' + 'media' + '/' + file_name)
	# client.action.resource_create(	
	#     package_id='ac335d1a-098c-4f18-882c-03950ddc5d7c',
	#     name = 'Postos de Combustíveis - Natal - RN - ' + date,
	#     description = 'Este arquivo contém as informações dos Postos de Combustíveis de Natal - RN.',
	#     format = 'json',
	#     upload = open(file_path_json, 'rb'),
	#     url = 'http://' + domain + '/' + 'media' + '/gas_stations_data.json')

def update_entity_attributes(request):
	orion_client = get_orion_client()
	entity_id = request.GET.get('entity_id', None)
	price = request.GET.get('price', None)
	star_votes1 = request.GET.get('star_votes[1]', None)
	star_votes2 = request.GET.get('star_votes[2]', None)
	star_votes3 = request.GET.get('star_votes[3]', None)
	star_votes4 = request.GET.get('star_votes[4]', None)
	star_votes5 = request.GET.get('star_votes[5]', None)
	dateUpdated = str(datetime.datetime.now(pytz.timezone('America/Recife')))
	attributes = '{ "last_update" : "' + dateUpdated + '", "price" : ' + price + ', "star_votes" : {"1":' + star_votes1 + ', "2":' + star_votes2 +', "3":' + star_votes3 + ', "4": ' + star_votes4  + ', "5": ' + star_votes5 + '}}'
	attrs = json.loads(attributes)
	response = {}
	try:
		orion_client.update_attributes(entity_id, attrs)
		response['code'] = 'OK'
	except:
		response['code'] = 'ERROR'
	domain = request.get_host()
	update_ckan_database_resource(domain, entity_id)
	return JsonResponse(response)

def update_ckan(request):
	domain = request.get_host()
	update_ckan_database_resource(domain)
	response = {'code': 'OK'}
	return JsonResponse(response) 

friendlygas_project/core/templates/core/base.html
<!doctype html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>FriendlyGas</title>

    <!-- Bootstrap core CSS -->
    <!--<link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">-->
    <link href="{% static 'stylesheets/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'stylesheets/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'stylesheets/freelancer.css' %}" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Map Icons -->
    <link rel="stylesheet" type="text/css" href="{% static 'dist/css/map-icons.css' %}">
    <script type="text/javascript" src="{% static 'dist/js/map-icons.js' %}"></script>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCFv3XU2PyXD81SFJZC8r8o3ffWrRdShDg"></script>

    <script src="{% static 'javascripts/jquery.js' %}"></script>
    <script src="{% static 'javascripts/popper.js' %}"></script>
    <script src="{% static 'javascripts/bootstrap.js' %}"></script>
    <script src="{% static 'javascripts/jquery.easing.js' %}"></script>
    <script src="{% static 'javascripts/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'javascripts/freelancer.js' %}"></script>

    <style>
        #gMapsDiv {
            height: 500px;
            width: 100%;
        }
        .customStar {
            color: yellow;
            -webkit-text-stroke-width: 1px;
            -webkit-text-stroke-color: orange;
        }
        #infoWindow {
            min-height: 60px;
            max-width: 200px;
        }
        #infoWindow p {
            font-size: 14px;
            margin-bottom: 5px;
        }
        .stars-font-size {
            font-size: 14px !important;
        }
    </style>

 
<body id="page-top">


<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top"><i class="fa fa-fire"></i> FriendlyGas</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <!--<li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#portfolio">Portfolio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#about">About</a>
                </li>-->
            </ul>
        </div>
    </div>
</nav>

{% block content %}{% endblock %}

<!-- Footer -->
<footer class="text-center">
    <div class="footer-below">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    Copyright &copy; FriendlyGas 2017
                </div>
            </div>
        </div>
    </div>
</footer>

<!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
<div class="scroll-top d-lg-none">
    <a class="btn btn-primary js-scroll-trigger" href="#page-top">
        <i class="fa fa-chevron-up"></i>
    </a>
</div>


</div>

</body>
</html>

friendlygas_project/core/templates/core/home.html
{% extends "core/base.html" %}

{% block content %}

<script>

    var MY_LOCALIZATION = "Minha Localização"

    function determineCheapestAndMoreExpensiveGasStations(data) {
        lowPrice = parseFloat(Object.values(window.data)[0].price)
        expensivePrice = parseFloat(Object.values(window.data)[0].price)
        $.each(data, function(key, value){
            if (parseFloat(value.price) < lowPrice) {
                lowPrice = parseFloat(value.price)
            }
            if (parseFloat(value.price) > expensivePrice) {
                expensivePrice = parseFloat(value.price)
            }
        });

        $.each(data, function(key, value){
            if (parseFloat(value.price) == lowPrice) {
                value.pinColor = "green"
            } else if (parseFloat(value.price) == expensivePrice) {
                value.pinColor = "red"
            } else {
                value.pinColor = "blue"
            }
        });
    }
    function getLocation() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(showPosition)
        } else {
            console.log("Geolocation is not supported by this browser.");
        }
    }

    function nearGasStations(position, map) {
        $.ajax({
            url: '{% url "core:near_gas_stations" %}',
            data: {
              'latitude': position.coords.latitude,
              'longitude': position.coords.longitude,
              'radius': 1500
            },
            dataType: 'json',
            success: function (data) {
                window.data = data

                determineCheapestAndMoreExpensiveGasStations(data)

                $.each(data, function(key, value){                        
                    var position = value.position.split(",").map(function (x) { return parseFloat(x); });
                    var uluru = {lat: position[0], lng: position[1]};
                    value.position = uluru;
                    value.id = key
                    createMarker(value, map)
                });
            },
            error: function(data){
                console.log(data);
            }
        });                 
    }         
    
    function showPosition(position) {
        var uluru = {lat: position.coords.latitude, lng: position.coords.longitude};
        var map = new google.maps.Map(document.getElementById('gMapsDiv'), {
            zoom: 15,
            center: uluru
        });
        
        marker_info = {
            name: MY_LOCALIZATION,
            position: uluru
        }

        createMarker(marker_info, map);
        nearGasStations(position, map);
        createCircle(uluru, map)
    }
    
    function createMarker(marker_info, map) {
        //console.log(marker_info)

        var starsMedia = calculateStarsMedia(marker_info.star_votes)

        var contentString, infowindow
        if (marker_info.name != MY_LOCALIZATION) {
            contentString = '<div id="infoWindow">'+
            '<div>'+
            '<p><span class="font-weight-bold">' + marker_info.name + '</span></p>' +
            '<p><span class="font-weight-bold">Preço:</span> R$ ' + marker_info.price + '</p>' +
            '<p class="stars-font-size">'

            for (i = 0; i < Math.floor(starsMedia); i++) {
                contentString += '<i class="fa fa-star"></i>'
            }

            for (i = 0; i < 5 - Math.floor(starsMedia); i++) {
               contentString += '<i class="fa fa-star-o"></i>'
            }

            contentString += ' (' + starsMedia +') </p> </div>'

            contentString += '<p><a href="#" data-toggle="modal" data-target="#myModal" id="' + marker_info.id + '" onclick="abrirModal(this.id)">Abasteci aqui</a></p></div>'

            infowindow = new google.maps.InfoWindow({
                content: contentString
            });
        }

        var icon
        if (marker_info.name != MY_LOCALIZATION) {
            //icon = "http://maps.google.com/mapfiles/kml/shapes/gas_stations.png?raw=true"
            icon = pinSymbol(marker_info)
        }

        var marker = new google.maps.Marker({
            position: marker_info.position,
            map: map,
            icon: icon
            //map_icon_label: '<span class="map-icon map-icon-gas-station"></span>'
        });

        if (marker_info.name != MY_LOCALIZATION) {
            marker.addListener('click', function() {
                infowindow.open(map, marker);
            });
        }

    }

    function pinSymbol(marker_info) {
      return {
        path: 'M 0,0 C -2,-20 -10,-22 -10,-30 A 10,10 0 1,1 10,-30 C 10,-22 2,-20 0,0 z',
        fillColor: marker_info.pinColor,
        fillOpacity: 1,
        strokeColor: '#000',
        strokeWeight: 2,
        scale: 1
      };
    }

    function createCircle(position, map) {
        var cityCircle = new google.maps.Circle({
            strokeColor: '#FF0000',
            strokeOpacity: 0.5,
            strokeWeight: 2,
            fillColor: '#FF0000',
            fillOpacity: 0.20,
            map: map,
            center: position,
            radius: 1500
        });
    }

    function calculateStarsMedia(star_votes) {
        var peso = 0
        var somaVotos = 0
        var media
        $.each(star_votes, function(key, value){
            peso = peso + (key * parseInt(value))
            somaVotos = somaVotos + parseInt(value)
        });
        media = parseFloat(peso / somaVotos).toFixed(2)
        return media
    }

    function abrirModal(id) {
        $('#entityId').val(id)
        $.each(data, function(key, value){                        
            if (key == id) {
                $('#myModal').find('#valorCombustivelModal').val(value.price)
                resetStars()
            }
        });
    }

    function updateStars(id) {
        resetStars()

        for (i = 1; i <= 5; i++) {
            var star = "star" + i
            $("#" + star).removeClass("fa-star-o")
            $("#" + star).addClass("fa-star")
            if (star == id) {
                $("#stars").val(i)
                break
            }
        }
    }

    function resetStars() {
        for (i = 1; i <= 5; i++) {
            $("#stars").val(0)
            var star = "star" + i
            $("#" + star).removeClass("fa-star")
            $("#" + star).addClass("fa-star-o")
        }
    }

    function sendEvaluation() {
        console.log("enviando...")

        var votesDict = {}

        $.each(window.data, function(key, value) {
            if (key == $('#entityId').val().toString()) {
                votesDict[1] = value.star_votes[1]
                votesDict[2] = value.star_votes[2]
                votesDict[3] = value.star_votes[3]
                votesDict[4] = value.star_votes[4]
                votesDict[5] = value.star_votes[5]
                votesDict[$("#stars").val()] = parseInt(value.star_votes[$("#stars").val()]) + 1
            }
        })

        $.ajax({
            url: '{% url "core:update_entity_attributes" %}',
            data: {
                'entity_id': $('#entityId').val().toString(),
                'price' : $("#valorCombustivelModal").val().toString(),
                'star_votes' : votesDict
            },
            dataType: 'json',
            success: function (data) {
                $("#myModal").modal('hide')
                getLocation()
            },
            error: function(data){
                $("#myModal").modal('hide')
                getLocation()
            }
        });
    }    
        
    $(document).ready(function(){
        getLocation()
    })
</script>

<div id="gMapsDiv"></div>

<!-- Modal -->
<div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <input type="hidden" name="entityId" id="entityId">
        <p class="text-center"> 
            Preço R$: <br/>
            <input type="text" required name="valorCombustivelModal" id="valorCombustivelModal"/>
        </p>
        <p class="text-center">
            Sua avaliação: <br/>
            <span style="font-size: 28px !important;">
                <i class="fa fa-star-o" id="star1" onmouseover="updateStars(this.id)"></i><i class="fa fa-star-o" id="star2" onmouseover="updateStars(this.id)"></i><i class="fa fa-star-o" id="star3" onmouseover="updateStars(this.id)"></i><i class="fa fa-star-o" id="star4" onmouseover="updateStars(this.id)"></i><i class="fa fa-star-o" id="star5" onmouseover="updateStars(this.id)"></i>
            </span>
            <input type="hidden" name="stars" id="stars">
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Fechar</button>
        <button type="button" class="btn btn-primary btn-sm" onclick="sendEvaluation()">Enviar</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}